### ISSUE TITLE
Present and document how to delete an e-imunisasi account

### ISSUE THREAD

**Issue by peltops** [peltops/e-imunisasi#123]

**Comment by rfaturriza** [comment]
- Go to [Firebase](https://console.firebase.google.com/u/0/project/eimunisasi-81ae1/overview) and choose eimunisasi project
<img src="https://github.com/peltops/e-imunisasi/assets/56538058/927ac757-86ef-44af-9352-e88938418afd" height=300>


- Go to Authentication menu
![Image](https://github.com/peltops/e-imunisasi/assets/56538058/b7b6004e-bf85-4ab7-bbd3-3bfeeda1d36b)


- Choose the account that you want to remove
![Image](https://github.com/peltops/e-imunisasi/assets/56538058/d0e905ee-281f-4177-8925-21c9abd8a9d9)


- Confirmation dialog will appear, then click delete
<img src="https://github.com/peltops/e-imunisasi/assets/56538058/86a259f5-7eae-42d2-9983-0933e21eeb17" height=200>


- If the account deleted, it will show the notification at the corner of the screen
<img src="https://github.com/peltops/e-imunisasi/assets/56538058/898d60ec-08a5-4075-87e5-a360b0fc5e85" width=50%>

**Comment by rfaturriza** [comment]
The problem is the data of users still available in firestore database. If we want to delete the data, we can do manually, but absolutely it will take longer time.

Firebase also provides the extension to delete users data in [Cloud Firestore](https://firebase.google.com/docs/firestore), [Realtime Database](https://firebase.google.com/docs/database), or [Cloud Storage](https://firebase.google.com/docs/storage) in your Firebase (https://extensions.dev/extensions/firebase/delete-user-data). But we must set the project to [Blaze (pay as you go) plan](https://firebase.google.com/pricing)

The doc of delete user data extension: https://firebase.google.com/docs/extensions/official/delete-user-data
